### ISSUE TITLE
UnknownTopicOrPartition on not yet created topic

### ISSUE THREAD

**Issue by mancioshell** [spicavigo/kafka-rust#167]
I'm using kafka-rust simple cosumer within a rust container togheter with a kakfa container.

This is my docker-compose.yml:
```
zookeeper:
  image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mediator-request:1:3"  
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
request-service:
    build:
      context:  ./RequestService      
    restart: always
    ports:
      - 8999:8999
    depends_on:
      - mongo-request
    command: ["/usr/src/app/wait_for_it.sh", "kafka:9092", "-t", "50", "--", "/usr/src/app/target/release/request_service"]
```
This is the simple consumer client took from kafka-rust example folder.

```
extern crate kafka;
extern crate env_logger;

use kafka::consumer::{Consumer, FetchOffset, GroupOffsetStorage};
use kafka::error::Error as KafkaError;
fn main() {
    env_logger::init().unwrap();

    let broker = "kafka:9092".to_owned();
    let topic = "mediator-request".to_owned();
    let group = "mediator-request-group".to_owned();

    if let Err(e) = consume_messages(group, topic, vec![broker]) {
        println!("Failed consuming messages: {}", e);
    }
}

fn consume_messages(group: String, topic: String, brokers: Vec<String>) -> Result<(), KafkaError> {
    let mut con = try!(
        Consumer::from_hosts(brokers)
            .with_topic(topic)
            .with_group(group)
            .with_fallback_offset(FetchOffset::Earliest)
            .with_offset_storage(GroupOffsetStorage::Kafka)
            .create()
    );

    loop {
        let mss = try!(con.poll());
        if mss.is_empty() {
            println!("No messages available right now.");
            return Ok(());
        }

        for ms in mss.iter() {
            for m in ms.messages() {
                println!("{}:{}@{}: {:?}", ms.topic(), ms.partition(), m.offset, m.value);
            }
            let _ = con.consume_messageset(ms);
        }
        try!(con.commit_consumed());
    }
}
```
In docker-compose i have specified to wait until kafka is ready to accept connections, before start kafka-rust client. But unfortunately i can't wait for kafka creation of 'mediator-topic', so my rust client exited with UnknownTopicOrPartition exception. 

Is there any workaround to address this particular issue?
