### ISSUE TITLE
Failed consuming messages: failed to lookup address information: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by stephenlb** [spicavigo/kafka-rust#177]
# Repo example does not work on MacOS or Docker.

```shell
cargo run --example example-consume
```
Fails with:
```shell
Failed consuming messages: failed to lookup address information: nodename nor servname provided, or not known
```

```shell
~/Downloads/kafka-rust-master$ rustc --version
rustc 1.38.0 (625451e37 2019-09-23)
~/Downloads/kafka-rust-master$ cargo --version
cargo 1.38.0 (23ef9a4ef 2019-08-20)
```

## Docker-Compose for Kafka

```shell
---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```

**Comment by stephenlb** [comment]
Config issue with Kafka / Docker.  Fixed.

**Comment by admwrd** [comment]
This is old, but the OP didn't offer the fix.

To anyone who sees this later and needs to know the correct way, add the following to the docker-compose config:

```yaml
    ports:
      - "127.0.0.1:29092:29092"
     environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
```
